blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/delete', views.post_delete, name='post_delete'),
    path('post/<int:pk>/like', views.post_like, name='post_like'),
    path('people/', views.people, name='people'),
    path('help/', views.help, name='help'),
    path('help/message_sent', views.message_sent, name='message_sent'),
    path('follow_unfollow', views.follow_unfollow, name='follow_unfollow'),
    path('u/<slug:username>/', views.user, name='user'),

]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('edit_profile/', views.EditProfile, name='edit_profile'),
]

ziger/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('chat/', include('chat.urls')),    
	path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.utils import timezone
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()

class UserPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    
    text = models.CharField(max_length = 512)
    created_at = models.DateTimeField(default=timezone.now)
    
    likes = models.ManyToManyField(User, blank=True, related_name='liked')

    replys = models.IntegerField(default=0)

    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='replies')
    
    def __str__(self):
        return "{} - {}".format(self.user, self.created_at)

    class Meta:
        ordering = ('-created_at',)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from uuid import uuid4

def upload_rename(instance, filename):
    ext = filename.split('.')[-1]
    if instance.pk:
        return 'profile_images/{}/{}.{}'.format(instance.pk, uuid4().hex, ext)
    else:
        pass

class CustomUser(AbstractUser):
    photo = models.ImageField(upload_to=upload_rename, blank=True, default='profile_images/none/default.png')
    bio = models.CharField(null=True, blank=True, max_length = 512)
    follows = models.ManyToManyField(   'self', #self reference
                                        related_name='followed_by', #facilitate searches
                                        symmetrical=False) #like twitter, followers are not unilateral
    def __str__(self):
        return self.username

blog/forms.py
from .models import UserPost
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Reset

class UserPostForm(forms.ModelForm):
    class Meta:
        model = UserPost
        fields = ('text',)

class ReplyForm(forms.ModelForm):
    class Meta:
        model = UserPost
        fields = ('text', 'parent')
    
class HelpForm(forms.Form):
    sender = forms.EmailField(required=True, label='Email')
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, label='Message')


    def __init__(self, *args, **kwargs):
        super(HelpForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Row(
                Column('sender', css_class='form-group col-md-6'),
                Column('subject', css_class='form-group col-md-6'),
                css_class='form-row'
            ),
            'message'
        )
        self.helper.add_input(Submit('submit', 'Send'))

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import get_user_model
User = get_user_model()

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'first_name', 'last_name', 'email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'photo',
            'email',
            'first_name',
            'last_name',
            'bio',
            'password'

        )

blog/views.py
from django.http import HttpResponseRedirect, HttpResponse, Http404, JsonResponse
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.conf import settings
from django.urls import reverse

from .forms import UserPostForm, ReplyForm, HelpForm
from .models import UserPost

import logging

User = get_user_model()

@login_required
def index(request):
    following_user_ids = []
    following_user_ids.append(request.user.id)

    for fol in request.user.follows.all():
        following_user_ids.append(fol.id)

    userposts = UserPost.objects.filter(user__in=following_user_ids)

    replies = []
    for up in userposts:
        replies += up.replies.all()

    if request.method == "POST":
        pform = UserPostForm(request.POST)

        if pform.is_valid():
            post = pform.save(commit=False)
            post.user = request.user
            post.published_date = timezone.now()
            post.save()

            return redirect('/')
    else:
        pform = UserPostForm()
    return render(request, 'blog/index.html', {'pform': pform, 'posts': userposts, 'replies': replies, 'user': request.user})

@login_required
def user(request, username=''):
    try:
        puser = User.objects.get(username=username)
    except User.DoesNotExist:
        raise Http404

    userposts = UserPost.objects.filter(user=puser.id)
    replies = []
    for up in userposts:
        replies += up.replies.all()

    if username == User.objects.get(id=request.user.id).username:
        return render(request, 'blog/user.html', {'puser': puser, 'userposts': userposts, 'replies': replies, })
    else:
        
        reqU = User.objects.get(id=request.user.id)
        following = reqU.follows.all()

        if puser in following:
            return render(request, 'blog/user.html', {'puser': puser, 'userposts': userposts, 'replies': replies, 'follow': True, })
        else:
            return render(request, 'blog/user.html', {'puser': puser, 'userposts': userposts, 'replies': replies, 'follow': False, })

@login_required
def post_detail(request, pk):
    post = get_object_or_404(UserPost, id=pk)
    replies = post.replies.all()

    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            post.replys += 1
            post.save()
            reply = form.save(commit=False)
            reply.user = request.user
            reply.published_date = timezone.now()
            reply.save()
            return redirect('/')
    else:
        replyForm = ReplyForm()
    return render(request, 'blog/post_detail.html', {'replyform': replyForm, 'post': post, 'replies': replies, 'user': request.user})

@login_required
def follow_unfollow(request):
    if request.method == "POST":
        follow_id = request.POST.get('follow', False)
        user = User.objects.get(id=follow_id)

        reqU = User.objects.get(id=request.user.id)
        following = reqU.follows.all()

        if user in following:
            reqU.follows.remove(user)
        else:
            reqU.follows.add(user)

        return redirect('u/{}'.format(user.username))

@login_required
def post_delete(request, pk):
    post = get_object_or_404(UserPost, id=pk)
    if post.user.id == request.user.id:
        post.delete()
    return redirect('/')

@login_required
def post_like_pl(request, pk):        
    post = get_object_or_404(UserPost, id=pk)

    likes = post.likes.all()

    if request.user in likes:
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)

    return redirect('/')

@login_required
def post_like(request, pk):
    try:
        post = get_object_or_404(UserPost, id=pk)
        likes = post.likes.all()

        if request.user in likes:
            post.likes.remove(request.user)
            data = {
                'likesCount': post.likes.count(),
                'liked': False,
                'status': 1
            }
        else:
            post.likes.add(request.user)
            data = {
                'likesCount': post.likes.count(),
                'liked': True,
                'status': 1
            }
    except:
        data = {
            'status': 0
        }

    return JsonResponse(data)

@login_required
def people(request):
    user_list = User.objects.all()
    return render(request, 'blog/people.html', {'user_list': user_list})

def help(request):
	if request.method == 'GET':
		email_form = HelpForm()
	else:
		email_form = HelpForm(request.POST)
		if email_form.is_valid():
			subject = email_form.cleaned_data['subject']
			message = email_form.cleaned_data['message']
			sender = email_form.cleaned_data['sender']

			try:
				send_mail(sender+' - '+subject, message, from_email=sender, recipient_list=['ziger.application@gmail.com'])
			except BadHeaderError:
				return HttpResponse("Error.")

			return redirect('message_sent')
	return render(request, 'blog/help.html', {'form': email_form})


def message_sent(request):
      messages.success(request, 'Message sent.')
      return redirect('index')

users/views.py
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import generic

User = get_user_model()

class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

@login_required
def EditProfile(request):
  if request.method == 'POST':
    form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)

    if form.is_valid():
      form.save()
      messages.success(request, 'Profile updated.')
      return redirect('/u/{}'.format(request.user.username))
    else:
      messages.warning(request, 'Not valid form.')
      return redirect('/u/{}'.format(request.user.username))

  else:
    form = CustomUserChangeForm(instance=request.user)
    return render(request, 'users/edit_profile.html', {'form': form})

blog/templates/blog/help.html
{% extends 'base.html' %}
{% load static %}

{% if user.is_authenticated %}
  {% block content %}
  <div class="col-md-8 mx-auto">
    <div class="card my-5">
      <div class="card-body">
        <h4 class="card-title text-center my-2">Need help? Send us an email</h4>
        <form class="my-4" method="post">
          {% csrf_token %}
          {% load crispy_forms_tags %}
          {{ form|crispy }}
          <button class="btn btn-lg btn-primary btn-block" type="submit">Send email</button>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
{% else %}
  {% block offcontblock %}
  <div class="col-md-8 mx-auto">
    <div class="card my-5">
      <div class="card-body">
        <h4 class="card-title text-center my-2">Need help? Send us an email</h4>
        <form class="my-4" method="post">
          {% csrf_token %}
          {% load crispy_forms_tags %}
          {{ form|crispy }}
          <button class="btn btn-lg btn-primary btn-block" type="submit">Send email</button>
        </form>
      </div>
    </div>
  </div>
  {% endblock %}
{% endif %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block rightcontblock %}

{# <!-- NEW USER POST --> #}

<div class="card bg-light text-center mx-3 my-5">
    <form method="POST" class="post-form">
        <div class="card-body">
            {% csrf_token %}
            {% load widget_tweaks %}
            <div class="form-group">
                {% render_field pform.text class+="form-control" placeholder+="New post" %}
            </div>
            <button type="submit" class="btn btn-primary btn-block">Post</button>
        </div>
    </form>
</div>

{# <!--  --> #}

<hr class="mx-3 my-3">

{# <!-- POSTS --> #}

{% load static %}
{% for post in posts %}

<div class="card bg-light mx-3">
    <div class="card-body">
        <p class="card-text">{{ post.text }}</p>
    </div>
    <div class="card-footer text-muted">
        <img class="rounded-circle" src="{{ post.user.photo.url }}" alt="{{ post.user.username }}" height="32" width="32">
        <a href="{% url 'user' username=post.user.username %}" class="badge badge-dark"> @{{ post.user.username }}</a>
        <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ post.created_at }}</a>

        <div class="btn-group btn-group-sm float-right" role="group" aria-label="Post Misc">
           
            {% if user in post.likes.all %}
                <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                    <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite</i>
                    <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
                </button>

            {% else %}
                <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                    <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite_border</i>
                    <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
                </button>
            {% endif %}

            <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-outline-dark">
                <i class="material-icons align-middle" role="presentation">reply</i>
                <span> {{ post.replys }} </span>
            </a>
            
            {% if post.user.id == user.pk %}
            <a href="{% url 'post_delete' pk=post.pk %}" class="btn btn-outline-dark">
                <i class="material-icons align-middle" role="presentation">delete</i>
            </a>
            {% endif %}

        </div>
    </div>
</div>

{% for reply in replies %}
{% if reply.parent_id == post.id %}

<div class="card bg-light ml-5 mr-3">
    <div class="card-body">
        <p class="card-text">{{ reply.text }}</p>
    </div>
    <div class="card-footer text-muted">
        <img class="rounded-circle" src="{{ reply.user.photo.url }}" alt="{{ reply.user.username }}" height="32" width="32">
        <a href="{% url 'user' username=reply.user.username %}" class="badge badge-dark"> @{{ reply.user }}</a>
        <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ reply.created_at }}</a>

        <div class="btn-group btn-group-sm float-right" role="group" aria-label="Reply Misc">            
            <a href="{% url 'post_detail' pk=reply.pk %}" class="btn btn-outline-dark">
                <i  class="material-icons align-middle" 
                    role="presentation">reply</i><span>{{ reply.replys }}</span></a>
        </div>
    </div>
</div>

{% endif %}
{% endfor %}

</br>

{% endfor %}

{% endblock %}

{% block js %}     
<script src="{% static 'js/blog.js' %}"></script>
{% endblock %}

blog/templates/blog/people.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-8 mx-auto my-5">
    
    {% for u in user_list %}
    <div class="card">
        <div class="card-body text-center">
            <img class="rounded-circle mx-auto mt-3" src="{{ u.photo.url }}" alt="{{ u.username }}" height="64" width="64">
            <h4 class="card-title my-2">{{ u.username }}</h4>
            <hr class="my-2">
            
            {% if u.id != user.id %}
            <a href="/u/{{ u.username }}" class="btn btn-secondary btn-block my-2">See Profile</a>
            <form action="/follow_unfollow" method="post">
                {% csrf_token %}
                <input type="hidden" name="follow" value="{{ u.id }}">

                {% if u in user.follows.all %}
                <button type="submit" class="btn btn-sm btn-outline-primary btn-block">Unfollow</button>
                {% else %}
                <button type="submit" class="btn btn-sm btn-primary btn-block">Follow</button>
                {% endif %}
            </form>
            {% else %}
            <a href="/u/{{ u.username }}" class="btn btn-outline-dark btn-block my-2">See Profile</a>
            <a href="{% url 'edit_profile' %}" class="btn btn-outline-dark btn-block">Edit Profile</a>
            {% endif %}

        </div>
    </div>
    <div class="my-3"></div>
    {% endfor %}

</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-lg-8 mx-auto my-5 order-first">
    {# <!-- POSTS --> #}

    <div class="card bg-light">
        <div class="card-body">
            <p class="card-text">{{ post.text }}</p>
        </div>
        <div class="card-footer text-muted">
            <img class="rounded-circle" src="{{ post.user.photo.url }}" alt="{{ post.user.username }}" height="32" width="32">
            <a href="/u/{{ post.user }}" class="badge badge-dark"> @{{ post.user }}</a>
            <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ post.created_at }}</a>
            <div class="btn-group btn-group-sm float-right" role="group" aria-label="Post Misc">
                
                {% if user in post.likes.all %}
                    <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                        <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite</i>
                        <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
                    </button>
                {% else %}
                    <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                        <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite_border</i>
                        <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
                    </button>
                {% endif %}

                <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-outline-dark">
                    <i class="material-icons align-middle" role="presentation">reply</i>
                    <span> {{ post.replys }} </span>
                </a>

                {% if post.user.id == user.pk %}
                <a href="{% url 'post_delete' pk=post.pk %}" class="btn btn-outline-dark">
                    <i class="material-icons align-middle" role="presentation">delete</i>
                </a>
                {% endif %}

            </div>
        </div>
        <div class="card-footer">
            <form method="POST">
                {% csrf_token %}
                {% load widget_tweaks %}
                <input type="hidden" id="id_parent" name="parent" value="{{ post.id }}">
                <div class="form-row">
                    <div class="col-8">
                        {% render_field replyform.text class+="form-control" placeholder+="Reply" %}
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Post reply</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    {% for reply in replies %}
    {% if reply.parent_id == post.id %}
        <div class="card bg-light ml-5">
            <div class="card-body">
                <p class="card-text">{{ reply.text }}</p>
            </div>
            <div class="card-footer text-muted">
                <img class="rounded-circle" src="{{ reply.user.photo.url }}" alt="{{ reply.user.username }}" height="32" width="32">
                <a href="{% url 'user' username=reply.user.username %}" class="badge badge-dark"> @{{ reply.user }}</a>
                <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ reply.created_at }}</a>
                
                <div class="btn-group btn-group-sm float-right" role="group" aria-label="Post Misc">
                
                {% if user in reply.likes.all %}
                    <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=reply.pk %}" id="like{{ reply.pk }}" data-id="{{ reply.pk }}">
                        <i class="material-icons align-middle" role="presentation" id="icon{{ reply.pk }}">favorite</i>
                        <span id="numlikes{{ reply.pk }}">{{ reply.likes.count }}</span>
                    </button>
                {% else %}
                    <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=reply.pk %}" id="like{{ reply.pk }}" data-id="{{ reply.pk }}">
                        <i class="material-icons align-middle" role="presentation" id="icon{{ reply.pk }}">favorite_border</i>
                        <span id="numlikes{{ reply.pk }}">{{ reply.likes.count }}</span>
                    </button>
                {% endif %}
        
                    <a href="{% url 'post_detail' pk=reply.pk %}" class="btn btn-outline-dark">
                        <i  class="material-icons align-middle" role="presentation">reply</i>
                        <span>{{ reply.replys }}</span>
                    </a>
                </div>
            </div>
        </div>    
    {% endif %}
    {% endfor %}
    </br>
</div>
{% endblock %}

{% block js %}     
<script src="{% static 'js/blog.js' %}"></script>
{% endblock %}

blog/templates/blog/social.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-md-8 mx-auto my-3">
    
    {% for u in user_list %}
    <div class="card">
        <div class="card-body text-center">
            
                <img class="rounded-circle mx-auto mt-3" src="{{ u.photo.url }}" alt="{{ u.username }}" height="64" width="64">
            
            <h4 class="card-title my-2">{{ u.username }}</h4>
            {% if u.id != user.id %}
            <a href="/u/{{ u.username }}" class="btn btn-secondary btn-block my-2">See Profile</a>
            <form action="/follow_unfollow" method="post">
                {% csrf_token %}
                <input type="hidden" name="follow" value="{{ u.id }}">

                {% if u in user.follows.all %}
                <button type="submit" class="btn btn-sm btn-outline-primary btn-block">Unfollow</button>
                {% else %}
                <button type="submit" class="btn btn-sm btn-primary btn-block">Follow</button>
                {% endif %}
            </form>
            {% else %}
            <a href="/u/{{ u.username }}" class="btn btn-outline-dark btn-block my-2">See Profile</a>
            <a href="{% url 'edit_profile' %}" class="btn btn-outline-dark btn-block">Edit Profile</a>
            {% endif %}
        </div>
    </div>
    <div class="my-3"></div>
    {% endfor %}



</div>

{% endblock %}

blog/templates/blog/user.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="col-md-8 mx-auto">

  <div class="card text-center mx-3 my-3">
    <img class="rounded-circle mx-auto mt-3" src="{{ puser.photo.url }}" alt="Card image" height="128" width="128">
    <div class="card-body">
      <h3 class="card-title">
        {% if puser.first_name %}
          {{ puser.first_name}}
        {% endif %}
        {% if puser.last_name %}
          {{ puser.last_name}}
        {% endif %}
      </h3>
      <h5 class="card-title">
        <a href="/u/{{ puser.username }}">
          @{{ puser.username }}
        </a>
      </h5>
      {% if puser.bio %}
      <p class="card-text">{{ puser.bio }}</p>
      {% endif %}
      <hr class="my-3">
      {% if puser.id != user.id %}
      <form action="/follow_unfollow" method="post">
        {% csrf_token %}
        <input type="hidden" name="follow" value="{{ puser.id }}">

        {% if follow %}
        <button type="submit" class="btn btn-outline-primary">Unfollow</button>
        {% else %}
        <button type="submit" class="btn btn-primary">Follow</button>
        {% endif %}
      </form>
      {% else %}
      <a href="{% url 'edit_profile' %}" class="btn btn-outline-dark">Edit Profile</a>
      {% endif %}

    </div>
  </div>

  {% for post in userposts %}
  <br>
  <div class="card bg-light mx-3">
    <div class="card-body">
      <p class="card-text">{{ post.text }}</p>
    </div>
    <div class="card-footer text-muted">

      <img class="rounded-circle" src="{{ post.user.photo.url }}" alt="{{ post.user.username }}" height="32" width="32">

      <a href="{% url 'user' username=post.user.username %}" class="badge badge-dark"> @{{ post.user }}</a>
      <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ post.created_at }}</a>

      <div class="btn-group btn-group-sm float-right" role="group" aria-label="Post Misc">
          {% if user in post.likes.all %}
            <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite</i>
                <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
            </button>
          {% else %}
            <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=post.pk %}" id="like{{ post.pk }}" data-id="{{ post.pk }}">
                <i class="material-icons align-middle" role="presentation" id="icon{{ post.pk }}">favorite_border</i>
                <span id="numlikes{{ post.pk }}">{{ post.likes.count }}</span>
            </button>
          {% endif %}
        <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-outline-dark">
          <i class="material-icons align-middle" role="presentation">reply</i>
          <span> {{ post.replys }} </span></a>
        {% if post.user.id == user.pk %}
        <a href="" class="btn btn-outline-dark">
          <i class="material-icons align-middle" role="presentation">delete</i>
          <span></span></a>
        {% endif %}
      </div>
    </div>
  </div>

  {% for reply in replies %}
  {% if reply.parent_id == post.id %}

  <div class="card bg-light ml-5 mr-3">
    <div class="card-body">
      <p class="card-text">{{ reply.text }}</p>
    </div>
    <div class="card-footer text-muted">
      <img class="rounded-circle" src="{{ reply.user.photo.url }}" alt="{{ reply.user.username }}" height="32" width="32">
      <a href="{% url 'user' username=reply.user.username %}" class="badge badge-dark"> @{{ reply.user }}</a>
      <a href="{% url 'post_detail' pk=post.pk %}" class="badge">{{ reply.created_at }}</a>

      <div class="btn-group btn-group-sm float-right" role="group" aria-label="Reply Misc">
        {% if user in reply.likes.all %}
          <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=reply.pk %}" id="like{{ reply.pk }}" data-id="{{ reply.pk }}">
            <i class="material-icons align-middle" role="presentation" id="icon{{ reply.pk }}">favorite</i>
            <span id="numlikes{{ reply.pk }}">{{ reply.likes.count }}</span>
          </button>
        {% else %}
          <button type="button" class="btn btn-outline-dark" href="{% url 'post_like' pk=reply.pk %}" id="like{{ reply.pk }}" data-id="{{ reply.pk }}">
            <i class="material-icons align-middle" role="presentation" id="icon{{ reply.pk }}">favorite_border</i>
            <span id="numlikes{{ reply.pk }}">{{ reply.likes.count }}</span>
          </button>
        {% endif %}
        <a href="{% url 'post_detail' pk=reply.pk %}" class="btn btn-outline-dark">
          <i class="material-icons align-middle" role="presentation">reply</i><span>{{ reply.replys }}</span></a>
      </div>
    </div>
  </div>

  {% endif %}
  {% endfor %}
  {% endfor %}

</div>
{% endblock %}

{% block js %}     
<script src="{% static 'js/blog.js' %}"></script>
{% endblock %}